2023-12-21 15:56:40,553 INFO    MainThread:27442 [wandb_setup.py:_flush():76] Configure stats pid to 27442
2023-12-21 15:56:40,555 INFO    MainThread:27442 [wandb_setup.py:_flush():76] Loading settings from /zhome/19/0/64415/.config/wandb/settings
2023-12-21 15:56:40,557 INFO    MainThread:27442 [wandb_setup.py:_flush():76] Loading settings from /work3/soeba/HALOS/wandb/settings
2023-12-21 15:56:40,558 INFO    MainThread:27442 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2023-12-21 15:56:40,559 INFO    MainThread:27442 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'esrgan_bones_v3-5.py', 'program': 'esrgan_bones_v3-5.py'}
2023-12-21 15:56:40,562 INFO    MainThread:27442 [wandb_init.py:_log_setup():461] Logging user logs to /work3/soeba/HALOS/wandb/run-20231221_155640-2tqvv3y9/logs/debug.log
2023-12-21 15:56:40,564 INFO    MainThread:27442 [wandb_init.py:_log_setup():462] Logging internal logs to /work3/soeba/HALOS/wandb/run-20231221_155640-2tqvv3y9/logs/debug-internal.log
2023-12-21 15:56:40,566 INFO    MainThread:27442 [wandb_init.py:init():495] calling init triggers
2023-12-21 15:56:40,567 INFO    MainThread:27442 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2023-12-21 15:56:40,568 INFO    MainThread:27442 [wandb_init.py:init():548] starting backend
2023-12-21 15:56:40,570 INFO    MainThread:27442 [wandb_init.py:init():552] setting up manager
2023-12-21 15:56:40,628 INFO    MainThread:27442 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-21 15:56:55,025 INFO    MainThread:27442 [wandb_init.py:init():558] backend started and connected
2023-12-21 15:56:55,046 INFO    MainThread:27442 [wandb_init.py:init():636] updated telemetry
2023-12-21 15:56:55,057 INFO    MainThread:27442 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2023-12-21 15:57:25,060 INFO    MainThread:27442 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2023-12-21 15:57:25,062 ERROR   MainThread:27442 [wandb_init.py:init():676] backend process timed out
2023-12-21 15:57:25,063 ERROR   MainThread:27442 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
